### ISSUE TITLE
Do we keep `irisc-design-software` repo up to date

### ISSUE THREAD

**Issue by asmialek** [HaraldMagnusson/irisc-obsw#3]
Suppose I change the name of name of the function in `downlink.h` from `init_downlink()` sugested by [`irisc-design-software` repo file](https://github.com/HaraldMagnusson/irisc-design-software/blob/master/provided_required_interfaces.txt), to `init_udp_socket()`, or just add some functions as interfaces, do I need to also change that in `irisc-design-software`?

**Comment by HaraldMagnusson** [comment]
The names of the components are according to design and the `init_` function is meant to initialize the whole component. Therefore it is preferable to use the same name so that initializing the `downlink` component is done by calling `init_downlink`. There is no problem with expanding the initialization by creating more functions that are called in the `init_` function. However to maintain simplicity looking at the component from the outside i would prefer keeping the name of initialization functions as design.

**Comment by asmialek** [comment]
The question was rather about whether do we update `irisc-design-software` repo as we change the code, but thanks, that's also insightful and I'll keep to it :D

**Comment by HaraldMagnusson** [comment]
My point was mostly to not change the function name in the first place, therefore the design would not need tp be updated.
